name: flash_food
description: Fast Food is a Flutter food delivery app that allows users to order food from a variety of local restaurants. The app is designed to be easy to use and user-friendly.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  flutter_svg: ^2.0.9
  pinput: ^3.0.1
  provider: ^6.0.5
  http: ^0.13.5
  shared_preferences: ^2.2.2
  file_picker: any
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0
  google_sign_in: ^6.1.5
  firebase_auth: ^4.7.0
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/svg/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
